[project]
name = "template"
version = "0.0.16"
description = "A copier template for Clearskies Akeyless Custom Service Producers/Rotators"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
