name: Tests

on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  run-tests-and-wait:
    uses: ./.github/workflows/run-tests.yml # <-- This calls the other file
